SELECT *
FROM (SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) AS A
WHERE A.AVERAGE_DURATION >= 7
ORDER BY A.AVERAGE_DURATION DESC, A.CAR_ID DESC