-- 코드를 입력하세요
SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF AS A
JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) AS B
ON A.SHIPMENT_ID = B.SHIPMENT_ID
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
LIMIT 3










# SELECT A.FLAVOR
# FROM FIRST_HALF AS A
# INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
#             FROM JULY
#             GROUP BY FLAVOR) AS B
# ON A.FLAVOR = B.FLAVOR
# ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC
# LIMIT 3