-- 코드를 입력하세요
SELECT INS.ANIMAL_ID AS ANIMAL_ID, INS.NAME AS NAME
FROM ANIMAL_INS AS INS
INNER JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME













# SELECT A.ANIMAL_ID AS ANIMAL_ID, A.NAME AS NAME
# FROM ANIMAL_INS AS A
# INNER JOIN ANIMAL_OUTS AS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.DATETIME > B.DATETIME
# ORDER BY A.DATETIME;