SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES AS A
JOIN (SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO) AS B
ON A.EMP_NO = B.EMP_NO
ORDER BY B.SCORE DESC
LIMIT 1;