-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS A
INNER JOIN (SELECT *
            FROM BOOK_SALES
            WHERE YEAR(SALES_DATE) = '2022' 
            AND MONTH(SALES_DATE) = '01') AS B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY
